# agent-harness-atlas — Makefile (harness-kit, stack-agnostic skeleton)
# Generated by harness-kit v1.
#
# This Makefile is intentionally stack-agnostic. Replace the placeholder
# command bodies below with your project's real commands. The TARGETS are
# the canonical names every harness-kit project exposes — agents and CI
# rely on these names, not on whatever your stack calls them natively.
#
# Quick reference:
#   make setup      install/refresh dependencies
#   make dev        run in dev mode
#   make test       run unit + integration tests
#   make e2e        run end-to-end tests (slow)
#   make lint       run linter
#   make typecheck  run type checker (or no-op if not applicable)
#   make build      build for production
#   make check      lint + typecheck + test + build (the bar)
#   make clean      remove build artifacts
#
# Optional harness scripts (not Make targets — call directly):
#   bash scripts/session-init.sh       # L06 read state + briefing
#   bash scripts/exit-clean.sh         # L12 5-dimension session-end check
#   bash scripts/validate-feature.sh <id>   # run a feature's verification command
#   cat .harness/bootstrap-prompt.txt  # re-read the bootstrap prompt

.PHONY: help \
        setup dev test e2e lint typecheck build check clean

help:
	@echo "agent-harness-atlas — common targets (harness-kit):"
	@echo ""
	@echo "  make setup         install dependencies"
	@echo "  make dev           run in dev mode"
	@echo "  make test          run unit + integration tests"
	@echo "  make e2e           run end-to-end tests"
	@echo "  make lint          run linter"
	@echo "  make typecheck     run type checker"
	@echo "  make build         build for production"
	@echo "  make check         lint + typecheck + test + build"
	@echo "  make clean         remove build artifacts"
	@echo ""
	@echo "Harness scripts (not Make targets — bash directly):"
	@echo "  bash scripts/session-init.sh       L06 briefing"
	@echo "  bash scripts/exit-clean.sh         L12 5-dim end-of-session check"
	@echo "  bash scripts/validate-feature.sh <id>   run a feature's verification"
	@echo "  cat  .harness/bootstrap-prompt.txt re-read the bootstrap prompt"
	@echo ""
	@echo "Or use the harness CLI directly:"
	@echo "  harness doctor     score the harness (5 subsystems + cold-start)"

# --- Project-specific targets (FILL IN with real commands for THIS project) ---

setup:
	@echo "TODO: replace with your dependency install command"
	@echo "  e.g. npm install   |   uv sync   |   cargo build   |   bundle install"
	@true

dev:
	@echo "TODO: replace with your dev runner"
	@echo "  e.g. npm run dev   |   uvicorn app:app --reload   |   cargo run"
	@true

test:
	@echo "TODO: replace with your test runner"
	@echo "  e.g. npm test   |   pytest -q   |   cargo test   |   go test ./..."
	@true

e2e:
	@bash scripts/e2e-check.sh

lint:
	@echo "TODO: replace with your linter (or use @true if N/A)"
	@true

typecheck:
	@echo "TODO: replace with your type checker (or use @true if N/A)"
	@true

build:
	@echo "TODO: replace with your build command (or use @true if N/A)"
	@true

check: lint typecheck test build
	@echo "✓ check passed"

clean:
	@echo "TODO: replace with your clean command"
	@rm -rf .cache .tmp coverage 2>/dev/null || true
