#!/usr/bin/env node
// build-data: compose src/meta.json + analysis/*.json into the SINGLE generated
// data module src/generated/atlas-data.ts that BOTH index.ts and agent.ts import.
// This is the single-source-of-truth step (F01). Fails fast on malformed data.
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DIMS = ["memory", "context", "skill", "cost", "sandbox", "multiagent"];

const meta = JSON.parse(readFileSync(resolve(ROOT, "src/meta.json"), "utf8"));
const order = meta.agentOrder;

const analysisDir = resolve(ROOT, "analysis");
const files = readdirSync(analysisDir).filter((f) => f.endsWith(".json"));

const byId = {};
for (const f of files) {
  const d = JSON.parse(readFileSync(resolve(analysisDir, f), "utf8"));
  // ---- fail-fast validation (build-time gate) ----
  const errs = [];
  if (!d.id) errs.push("missing id");
  if (!["source", "docs"].includes(d.evidenceBasis)) errs.push(`bad evidenceBasis ${d.evidenceBasis}`);
  if (d.evidenceBasis === "docs" && !d.evidenceNote?.zh) errs.push("docs basis needs evidenceNote");
  if (d.evidenceBasis === "source" && !d.repo) errs.push("source basis needs repo");
  const cellKeys = Object.keys(d.cells || {}).sort();
  if (cellKeys.join(",") !== [...DIMS].sort().join(",")) errs.push(`cells keys ${cellKeys} != dims`);
  for (const dim of DIMS) {
    const c = d.cells?.[dim];
    if (!c) { errs.push(`${dim} missing`); continue; }
    if (c.score !== null && (typeof c.score !== "number" || c.score < 1 || c.score > 100))
      errs.push(`${dim}.score invalid: ${c.score}`);
    if (!c.zh?.trim() || !c.en?.trim()) errs.push(`${dim} empty zh/en`);
    if (!Array.isArray(c.citations) || c.citations.length === 0) errs.push(`${dim} no citations`);
    // normalize citation L-form: accept "p:123", "p:123-456", "p:L1", "p:L1-L9", URLs
    c.citations = c.citations.map((cit) => {
      if (/^https?:\/\//.test(cit)) return cit;
      const m = cit.match(/^(.+?):L?(\d+)(?:-L?(\d+))?$/);
      if (!m) return cit;
      return m[3] ? `${m[1]}:L${m[2]}-L${m[3]}` : `${m[1]}:L${m[2]}`;
    });
  }
  if (errs.length) {
    console.error(`✗ analysis/${f} invalid:\n  - ${errs.join("\n  - ")}`);
    process.exit(1);
  }
  byId[d.id] = d;
}

// order agents per meta.agentOrder
const agents = order.map((id) => {
  if (!byId[id]) { console.error(`✗ meta.agentOrder lists "${id}" but analysis/${id}.json missing`); process.exit(1); }
  return byId[id];
});
const extra = Object.keys(byId).filter((id) => !order.includes(id));
if (extra.length) { console.error(`✗ analysis files not in agentOrder: ${extra.join(", ")}`); process.exit(1); }

const META = { updated: meta.updated, version: meta.version, sourceNote: meta.sourceNote };

const banner = `// AUTO-GENERATED by scripts/build-data.mjs — DO NOT EDIT.
// Single source of truth: composed from src/meta.json + analysis/*.json.
// Both index.ts and agent.ts import ATLAS from here. Re-run \`npm run build\`.\n`;
const body = `import type { AgentAnalysis, Meta } from "../types";

export const META: Meta = ${JSON.stringify(META, null, 2)};

export const AGENTS: AgentAnalysis[] = ${JSON.stringify(agents, null, 2)};
`;

mkdirSync(resolve(ROOT, "src/generated"), { recursive: true });
writeFileSync(resolve(ROOT, "src/generated/atlas-data.ts"), banner + body);
console.log(`✓ build-data: ${agents.length} agents → src/generated/atlas-data.ts (order: ${order.join(", ")})`);
