#!/usr/bin/env bash
# L12 exit-clean: 5-dimension session-end check.
# Generated by harness-kit. Customize the per-stack commands as needed.
#
# Tunables (env vars):
#   HARNESS_PROGRESS_MAX_AGE_HOURS  fail when PROGRESS.md is older than this
#                                   many hours (default 168 = 7 days; set 0
#                                   to never fail on age, only warn).

set -uo pipefail

cd "$(dirname "$0")/.." || exit 1

PROGRESS_MAX_AGE="${HARNESS_PROGRESS_MAX_AGE_HOURS:-168}"

PASS=0
FAIL=0
WARN=0

check() {
  local name="$1"; shift
  if "$@" >/dev/null 2>&1; then
    echo "  ✓ $name"
    PASS=$((PASS + 1))
  else
    echo "  ✗ $name"
    FAIL=$((FAIL + 1))
  fi
}

echo ""
echo "▸ exit-clean: 5-dimension check"
echo ""

# 1. build passes
check "build"          make -n build && make build

# 2. tests pass
check "tests"          make -n test && make test

# 3. progress recorded — PROGRESS.md exists; recency is a warning by default.
#    Use HARNESS_PROGRESS_MAX_AGE_HOURS to make staleness a hard fail.
if [ -f PROGRESS.md ]; then
  AGE=$(( ( $(date +%s) - $(stat -f %m PROGRESS.md 2>/dev/null || stat -c %Y PROGRESS.md) ) / 3600 ))
  if [ "$PROGRESS_MAX_AGE" -gt 0 ] && [ "$AGE" -gt "$PROGRESS_MAX_AGE" ]; then
    echo "  ✗ progress (${AGE}h old — exceeds HARNESS_PROGRESS_MAX_AGE_HOURS=${PROGRESS_MAX_AGE})"
    FAIL=$((FAIL + 1))
  elif [ "$AGE" -gt 24 ]; then
    echo "  ⚠ progress (${AGE}h old — stamp it if you've done substantive work)"
    WARN=$((WARN + 1))
    PASS=$((PASS + 1))
  else
    echo "  ✓ progress (updated ${AGE}h ago)"
    PASS=$((PASS + 1))
  fi
else
  echo "  ✗ progress (PROGRESS.md missing)"
  FAIL=$((FAIL + 1))
fi

# 4. no stale artifacts
STALE=$(find . -maxdepth 4 \
  -not -path './node_modules/*' \
  -not -path './.git/*' \
  -not -path './dist/*' \
  -not -path './build/*' \
  -not -path './.venv/*' \
  -not -path './__pycache__/*' \
  \( -name 'debug-*.log' -o -name '*.tmp' -o -name '*.swp' -o -name 'scratch-*' \) \
  2>/dev/null | head -10)
if [ -z "$STALE" ]; then
  echo "  ✓ no-stale-artifacts"
  PASS=$((PASS + 1))
else
  echo "  ✗ no-stale-artifacts ($(echo "$STALE" | wc -l | tr -d ' ') file(s)):"
  echo "$STALE" | sed 's/^/      /'
  FAIL=$((FAIL + 1))
fi

# 5. startup path callable
check "startup-path"   make -n setup

echo ""
if [ "$WARN" -gt 0 ]; then
  echo "  ${PASS} passed (${WARN} warn), ${FAIL} failed"
else
  echo "  ${PASS} passed, ${FAIL} failed"
fi
echo ""

if [ "$FAIL" -gt 0 ]; then
  echo "✗ Not clean. Fix before next handoff (L12)."
  exit 1
fi

echo "✓ Clean. Safe to end session."
exit 0
