#!/usr/bin/env python3
"""One-off: emit src/site.ts (presentation constants) from the designer template
JSON, preserving the designer's exact ICONS/BRANDS/DIMENSIONS/BANDS/UI byte-for-byte.
Per-agent grounded data does NOT live here — it comes from analysis/*.json at build."""
import json

A = json.load(open("/tmp/atlas-template.json"))

def js(v):  # JSON is valid TS literal syntax
    return json.dumps(v, ensure_ascii=False, indent=2)

# Update the Pi vendor in DIMENSIONS? No — DIMENSIONS has no vendor. Good.
dimensions = A["DIMENSIONS"]
bands = A["BANDS"]
pending = A["PENDING"]
ui = A["UI"]
icons = A["ICONS"]
brands = A["BRANDS"]

out = '''// AUTO-GENERATED by scripts/gen-site-ts.py from the Open Design template.
// Presentation constants ONLY (icons, brand colors, dimension labels, score
// bands, UI i18n copy). Per-agent grounded data comes from analysis/*.json via
// scripts/build-data.mjs — NOT here. Do not hand-edit; re-run the generator.
/* biome-ignore-all lint/suspicious/noControlCharactersInRegex: n/a */

export type Lang = "zh" | "en";
export type Bilingual = { zh: string; en: string };

export interface Dimension {
  id: string;
  zh: string;
  en: string;
  short: string;
  desc_zh: string;
  desc_en: string;
}

export interface Band {
  min: number;
  cvar: string;
  zh: string;
  en: string;
}

export interface Brand {
  bg: string;
  fg: string;
  mono?: boolean;
}

export const DIMENSIONS: Dimension[] = %s;

export const BANDS: Band[] = %s;

export const PENDING = %s as { cvar: string; zh: string; en: string };

export const ICONS: Record<string, string> = %s;

export const BRANDS: Record<string, Brand> = %s;

export const UI: Record<string, Bilingual> = %s;
''' % (js(dimensions), js(bands), js(pending), js(icons), js(brands), js(ui))

with open("src/site.ts", "w") as f:
    f.write(out)
print("wrote src/site.ts:", len(out), "bytes")
print("  DIMENSIONS:", [d["id"] for d in dimensions])
print("  ICONS/BRANDS:", len(icons), len(brands), "| UI keys:", len(ui))
