// AUTO-GENERATED by scripts/gen-site-ts.py from the Open Design template.
// Presentation constants ONLY (icons, brand colors, dimension labels, score
// bands, UI i18n copy). Per-agent grounded data comes from analysis/*.json via
// scripts/build-data.mjs — NOT here.
// NOTE: BANDS thresholds were hand-calibrated (85 卓越 / 70 扎实 / 60 可用 /
// <60 薄弱) and the one-off /tmp template the generator read no longer exists,
// so edit BANDS here directly — do NOT regenerate over it. Other blocks
// (ICONS/BRANDS/DIMENSIONS/UI) remain generator-owned; don't hand-edit those.
/* biome-ignore-all lint/suspicious/noControlCharactersInRegex: n/a */

export type Lang = "zh" | "en";
export type Bilingual = { zh: string; en: string };

export interface Dimension {
  id: string;
  zh: string;
  en: string;
  short: string;
  desc_zh: string;
  desc_en: string;
}

export interface Band {
  min: number;
  cvar: string;
  zh: string;
  en: string;
}

export interface Brand {
  bg: string;
  fg: string;
  mono?: boolean;
}

export const DIMENSIONS: Dimension[] = [
  {
    "id": "memory",
    "zh": "持久记忆",
    "en": "Memory",
    "short": "Mem",
    "desc_zh": "跨会话长期记忆与持久化层",
    "desc_en": "Cross-session long-term memory & persistence"
  },
  {
    "id": "context",
    "zh": "上下文压缩",
    "en": "Context Mgmt",
    "short": "Ctx",
    "desc_zh": "上下文窗口管理与压缩 / 摘要策略",
    "desc_en": "Context window management & compaction"
  },
  {
    "id": "skill",
    "zh": "技能扩展",
    "en": "Skills / Tools",
    "short": "Skill",
    "desc_zh": "工具 / 技能 / 插件扩展机制",
    "desc_en": "Tool / skill / plugin extension mechanism"
  },
  {
    "id": "cost",
    "zh": "成本效率",
    "en": "Cost / Tokens",
    "short": "Cost",
    "desc_zh": "token 效率与成本控制",
    "desc_en": "Token efficiency & cost control"
  },
  {
    "id": "sandbox",
    "zh": "权限沙箱",
    "en": "Permission/Sandbox",
    "short": "Sbx",
    "desc_zh": "权限模型与沙箱隔离",
    "desc_en": "Permission model & sandbox isolation"
  },
  {
    "id": "multiagent",
    "zh": "多 Agent 编排",
    "en": "Multi-agent",
    "short": "Multi",
    "desc_zh": "派生子 agent、并行任务与 agent 间协作",
    "desc_en": "Sub-agent spawning, parallel tasks & agent coordination"
  }
];

export const BANDS: Band[] = [
  {
    "min": 85,
    "cvar": "exceptional",
    "zh": "卓越",
    "en": "Exceptional"
  },
  {
    "min": 70,
    "cvar": "strong",
    "zh": "扎实",
    "en": "Strong"
  },
  {
    "min": 60,
    "cvar": "functional",
    "zh": "可用",
    "en": "Functional"
  },
  {
    "min": 1,
    "cvar": "broken",
    "zh": "薄弱",
    "en": "Broken"
  }
];

export const PENDING = {
  "cvar": "pending",
  "zh": "待填",
  "en": "Pending"
} as { cvar: string; zh: string; en: string };

export const ICONS: Record<string, string> = {
  "claude-code": "<svg viewBox=\"0 0 24 24\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M12 1.6c.5 0 .9.4.9.9l.5 6.2 4.4-4.4a.9.9 0 0 1 1.3 1.3l-4.4 4.4 6.2.5a.9.9 0 0 1 0 1.8l-6.2.5 4.4 4.4a.9.9 0 0 1-1.3 1.3l-4.4-4.4-.5 6.2a.9.9 0 0 1-1.8 0l-.5-6.2-4.4 4.4a.9.9 0 0 1-1.3-1.3l4.4-4.4-6.2-.5a.9.9 0 0 1 0-1.8l6.2-.5L4.8 5.6a.9.9 0 0 1 1.3-1.3l4.4 4.4.5-6.2c0-.5.5-.9.9-.9Z\"/></svg>",
  "codex": "<svg viewBox=\"0 0 24 24\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M21.3 9.9a5.4 5.4 0 0 0-.5-4.5 5.5 5.5 0 0 0-5.9-2.6A5.4 5.4 0 0 0 6.8 3.9a5.4 5.4 0 0 0-3.6 2.6 5.5 5.5 0 0 0 .7 6.4 5.4 5.4 0 0 0 .5 4.5 5.5 5.5 0 0 0 5.9 2.6 5.4 5.4 0 0 0 8.1-1.7 5.4 5.4 0 0 0 3.6-2.6 5.5 5.5 0 0 0-.7-6.4Zm-8 11.2a4 4 0 0 1-2.6-.9l3.6-2.1a.6.6 0 0 0 .3-.5v-5.1l1.5.9v4.1a4 4 0 0 1-2.8 3.6Zm-8.7-3.7a4 4 0 0 1-.5-2.7l3.6 2.1a.6.6 0 0 0 .6 0l4.4-2.5v1.8l-3.8 2.2a4 4 0 0 1-4.3-.9ZM4 8.5a4 4 0 0 1 2-1.7v4.2a.6.6 0 0 0 .3.5l4.4 2.5-1.5.9-3.8-2.2A4 4 0 0 1 4 8.5Zm12.5 2.9-4.4-2.6 1.5-.8 3.8 2.2a4 4 0 0 1-.6 7.2v-4.3a.6.6 0 0 0-.3-.5Zm1.5-2.2-3.6-2.1a.6.6 0 0 0-.6 0L9.4 7.6V5.8l3.8-2.2a4 4 0 0 1 5.9 4.1Zm-9.6 3-1.5-.9V6.2a4 4 0 0 1 6.6-3.1L10.5 5.2a.6.6 0 0 0-.3.5Zm.8-1.8 2-1.1 2 1.1v2.3l-2 1.1-2-1.1Z\"/></svg>",
  "pi": "<svg viewBox=\"0 0 24 24\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M4.2 6.5h15.6a.9.9 0 0 1 0 1.8h-2.3v8.1c0 .5.2.8.6.8s.6-.2.7-.6a.85.85 0 0 1 1.7.3c-.2 1.3-1.1 2.1-2.4 2.1-1.5 0-2.4-1-2.4-2.6V8.3h-3.6v9.9a.9.9 0 0 1-1.8 0V8.3H6.3a.9.9 0 0 1 0-1.8Z\"/></svg>",
  "opencode": "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.1\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"M8.5 8 5 11.7l3.5 3.7\"/><path d=\"M15.5 8l3.5 3.7-3.5 3.7\"/><path d=\"M7 19h10\"/></svg>",
  "cursor": "<svg viewBox=\"0 0 24 24\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M12 2.3 3.7 7v10L12 21.7 20.3 17V7L12 2.3Zm6.3 5.1L12 11.1 5.7 7.4 12 3.8l6.3 3.6ZM5.2 8.8l6.1 3.5v7.1l-6.1-3.5V8.8Zm7.6 10.6v-7.1l6-3.5v7.1l-6 3.5Z\"/></svg>",
  "aider": "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><rect x=\"3\" y=\"4.5\" width=\"18\" height=\"15\" rx=\"2.2\"/><path d=\"M7 9.5l2.6 2.5L7 14.5\"/><path d=\"M12.5 15h4\"/></svg>",
  "cline": "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.1\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"M9 5.5C6 7 4.5 9.3 4.5 12s1.5 5 4.5 6.5\"/><path d=\"M15 5.5c3 1.5 4.5 3.8 4.5 6.5s-1.5 5-4.5 6.5\"/><circle cx=\"12\" cy=\"12\" r=\"1.4\" fill=\"currentColor\" stroke=\"none\"/></svg>",
  "gemini-cli": "<svg viewBox=\"0 0 24 24\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M12 2c.3 4.7 2.3 7.7 7 8-4.7.3-6.7 3.3-7 8-.3-4.7-2.3-7.7-7-8 4.7-.3 6.7-3.3 7-8Z\"/></svg>"
};

export const BRANDS: Record<string, Brand> = {
  "claude-code": {
    "bg": "#D97757",
    "fg": "#ffffff"
  },
  "codex": {
    "bg": "#0D0D0D",
    "fg": "#ffffff",
    "mono": true
  },
  "pi": {
    "bg": "#6B6864",
    "fg": "#ffffff"
  },
  "opencode": {
    "bg": "#121212",
    "fg": "#ffffff",
    "mono": true
  },
  "cursor": {
    "bg": "#0A0A0A",
    "fg": "#ffffff",
    "mono": true
  },
  "aider": {
    "bg": "#3FA45B",
    "fg": "#ffffff"
  },
  "cline": {
    "bg": "#2B2F36",
    "fg": "#ffffff",
    "mono": true
  },
  "gemini-cli": {
    "bg": "#1B72E8",
    "fg": "#ffffff"
  }
};

export const UI: Record<string, Bilingual> = {
  "title": {
    "zh": "Agent Harness 图鉴",
    "en": "Agent Harness Atlas"
  },
  "subtitle": {
    "zh": "主流 AI 编码 Agent 的 harness 能力对比",
    "en": "Harness capability comparison of mainstream AI coding agents"
  },
  "kicker": {
    "zh": "5 维 Harness 评测",
    "en": "5-Dim Harness Review"
  },
  "source": {
    "zh": "源码 + 官方文档分析",
    "en": "Source-code + official-docs analysis"
  },
  "matrix": {
    "zh": "能力矩阵",
    "en": "Capability Matrix"
  },
  "matrixSub": {
    "zh": "8 个 agent × 5 个维度",
    "en": "8 agents × 5 dimensions"
  },
  "legend": {
    "zh": "分数 0–100",
    "en": "Score 0–100"
  },
  "agentCol": {
    "zh": "Agent",
    "en": "Agent"
  },
  "scoreCol": {
    "zh": "综合",
    "en": "Overall"
  },
  "viewDetail": {
    "zh": "详情",
    "en": "Detail"
  },
  "backHome": {
    "zh": "返回矩阵",
    "en": "Back to matrix"
  },
  "updatedLabel": {
    "zh": "更新",
    "en": "Updated"
  },
  "evidence": {
    "zh": "证据指向",
    "en": "Evidence"
  },
  "conclusion": {
    "zh": "结论",
    "en": "Conclusion"
  },
  "vendor": {
    "zh": "厂商",
    "en": "Vendor"
  },
  "impl": {
    "zh": "实现",
    "en": "Built in"
  },
  "pending": {
    "zh": "待填",
    "en": "Pending"
  },
  "verdict": {
    "zh": "总评",
    "en": "Verdict"
  },
  "keep": {
    "zh": "亮点",
    "en": "strength"
  },
  "fix": {
    "zh": "不足",
    "en": "gap"
  },
  "testedVer": {
    "zh": "评测版本",
    "en": "Tested version"
  },
  "dimReports": {
    "zh": "逐维度报告",
    "en": "Dimension reports"
  },
  "dimReportsEn": {
    "zh": "每个维度的证据",
    "en": "Evidence per axis"
  },
  "radarLabel": {
    "zh": "评分雷达",
    "en": "Score Radar"
  },
  "overallLabel": {
    "zh": "综合",
    "en": "Overall"
  },
  "band": {
    "zh": "分段",
    "en": "band"
  },
  "disclaimer": {
    "zh": "当前为框架样本，分数与结论为占位估值，证据指向待填真实源码 / 文档分析。",
    "en": "Framework sample — scores & conclusions are placeholder estimates pending real source / doc analysis."
  },
  "dimCompare": {
    "zh": "在矩阵中横向对比",
    "en": "Compare in the matrix"
  },
  "themeLight": {
    "zh": "浅色",
    "en": "Light"
  },
  "themeDark": {
    "zh": "深色",
    "en": "Dark"
  },
  "weekly": {
    "zh": "每周更新",
    "en": "Updated weekly"
  }
};
