// AUTO-GENERATED by scripts/gen-site-ts.py from the Open Design template.
// Presentation constants ONLY (icons, brand colors, dimension labels, score
// bands, UI i18n copy). Per-agent grounded data comes from analysis/*.json via
// scripts/build-data.mjs — NOT here.
// NOTE: BANDS thresholds were hand-calibrated (85 卓越 / 70 扎实 / 60 可用 /
// <60 薄弱) and the one-off /tmp template the generator read no longer exists,
// so edit BANDS here directly — do NOT regenerate over it. Other blocks
// (ICONS/BRANDS/DIMENSIONS/UI) remain generator-owned; don't hand-edit those.
/* biome-ignore-all lint/suspicious/noControlCharactersInRegex: n/a */

export type Lang = "zh" | "en";
export type Bilingual = { zh: string; en: string };

export interface Dimension {
  id: string;
  zh: string;
  en: string;
  short: string;
  desc_zh: string;
  desc_en: string;
}

export interface Band {
  min: number;
  cvar: string;
  zh: string;
  en: string;
}

export interface Brand {
  bg: string;
  fg: string;
  mono?: boolean;
}

export const DIMENSIONS: Dimension[] = [
  {
    "id": "memory",
    "zh": "持久记忆",
    "en": "Memory",
    "short": "Mem",
    "desc_zh": "跨会话长期记忆与持久化层",
    "desc_en": "Cross-session long-term memory & persistence"
  },
  {
    "id": "context",
    "zh": "上下文压缩",
    "en": "Context Mgmt",
    "short": "Ctx",
    "desc_zh": "上下文窗口管理与压缩 / 摘要策略",
    "desc_en": "Context window management & compaction"
  },
  {
    "id": "skill",
    "zh": "技能扩展",
    "en": "Skills / Tools",
    "short": "Skill",
    "desc_zh": "工具 / 技能 / 插件扩展机制",
    "desc_en": "Tool / skill / plugin extension mechanism"
  },
  {
    "id": "cost",
    "zh": "成本效率",
    "en": "Cost / Tokens",
    "short": "Cost",
    "desc_zh": "token 效率与成本控制",
    "desc_en": "Token efficiency & cost control"
  },
  {
    "id": "sandbox",
    "zh": "权限沙箱",
    "en": "Permission/Sandbox",
    "short": "Sbx",
    "desc_zh": "权限模型与沙箱隔离",
    "desc_en": "Permission model & sandbox isolation"
  },
  {
    "id": "multiagent",
    "zh": "多 Agent 编排",
    "en": "Multi-agent",
    "short": "Multi",
    "desc_zh": "派生子 agent、并行任务与 agent 间协作",
    "desc_en": "Sub-agent spawning, parallel tasks & agent coordination"
  }
];

export const BANDS: Band[] = [
  {
    "min": 85,
    "cvar": "exceptional",
    "zh": "卓越",
    "en": "Exceptional"
  },
  {
    "min": 70,
    "cvar": "strong",
    "zh": "扎实",
    "en": "Strong"
  },
  {
    "min": 60,
    "cvar": "functional",
    "zh": "可用",
    "en": "Functional"
  },
  {
    "min": 1,
    "cvar": "broken",
    "zh": "薄弱",
    "en": "Broken"
  }
];

export const PENDING = {
  "cvar": "pending",
  "zh": "待填",
  "en": "Pending"
} as { cvar: string; zh: string; en: string };

export const ICONS: Record<string, string> = {
  "claude-code": "<svg viewBox=\"0 0 24 24\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"m4.7144 15.9555 4.7174-2.6471.079-.2307-.079-.1275h-.2307l-.7893-.0486-2.6956-.0729-2.3375-.0971-2.2646-.1214-.5707-.1215-.5343-.7042.0546-.3522.4797-.3218.686.0608 1.5179.1032 2.2767.1578 1.6514.0972 2.4468.255h.3886l.0546-.1579-.1336-.0971-.1032-.0972L6.973 9.8356l-2.55-1.6879-1.3356-.9714-.7225-.4918-.3643-.4614-.1578-1.0078.6557-.7225.8803.0607.2246.0607.8925.686 1.9064 1.4754 2.4893 1.8336.3643.3035.1457-.1032.0182-.0728-.164-.2733-1.3539-2.4467-1.445-2.4893-.6435-1.032-.17-.6194c-.0607-.255-.1032-.4674-.1032-.7285L6.287.1335 6.6997 0l.9957.1336.419.3642.6192 1.4147 1.0018 2.2282 1.5543 3.0296.4553.8985.2429.8318.091.255h.1579v-.1457l.1275-1.706.2368-2.0947.2307-2.6957.0789-.7589.3764-.9107.7468-.4918.5828.2793.4797.686-.0668.4433-.2853 1.8517-.5586 2.9021-.3643 1.9429h.2125l.2429-.2429.9835-1.3053 1.6514-2.0643.7286-.8196.85-.9046.5464-.4311h1.0321l.759 1.1293-.34 1.1657-1.0625 1.3478-.8804 1.1414-1.2628 1.7-.7893 1.36.0729.1093.1882-.0183 2.8535-.607 1.5421-.2794 1.8396-.3157.8318.3886.091.3946-.3278.8075-1.967.4857-2.3072.4614-3.4364.8136-.0425.0304.0486.0607 1.5482.1457.6618.0364h1.621l3.0175.2247.7892.522.4736.6376-.079.4857-1.2142.6193-1.6393-.3886-3.825-.9107-1.3113-.3279h-.1822v.1093l1.0929 1.0686 2.0035 1.8092 2.5075 2.3314.1275.5768-.3218.4554-.34-.0486-2.2039-1.6575-.85-.7468-1.9246-1.621h-.1275v.17l.4432.6496 2.3436 3.5214.1214 1.0807-.17.3521-.6071.2125-.6679-.1214-1.3721-1.9246L14.38 17.959l-1.1414-1.9428-.1397.079-.674 7.2552-.3156.3703-.7286.2793-.6071-.4614-.3218-.7468.3218-1.4753.3886-1.9246.3157-1.53.2853-1.9004.17-.6314-.0121-.0425-.1397.0182-1.4328 1.9672-2.1796 2.9446-1.7243 1.8456-.4128.164-.7164-.3704.0667-.6618.4008-.5889 2.386-3.0357 1.4389-1.882.929-1.0868-.0062-.1579h-.0546l-6.3385 4.1164-1.1293.1457-.4857-.4554.0608-.7467.2307-.2429 1.9064-1.3114Z\"/></svg>",
  "codex": "<svg viewBox=\"0 0 24 24\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M22.2819 9.8211a5.9847 5.9847 0 0 0-.5157-4.9108 6.0462 6.0462 0 0 0-6.5098-2.9A6.0651 6.0651 0 0 0 4.9807 4.1818a5.9847 5.9847 0 0 0-3.9977 2.9 6.0462 6.0462 0 0 0 .7427 7.0966 5.98 5.98 0 0 0 .511 4.9107 6.051 6.051 0 0 0 6.5146 2.9001A5.9847 5.9847 0 0 0 13.2599 24a6.0557 6.0557 0 0 0 5.7718-4.2058 5.9894 5.9894 0 0 0 3.9977-2.9001 6.0557 6.0557 0 0 0-.7475-7.0729zm-9.022 12.6081a4.4755 4.4755 0 0 1-2.8764-1.0408l.1419-.0804 4.7783-2.7582a.7948.7948 0 0 0 .3927-.6813v-6.7369l2.02 1.1686a.071.071 0 0 1 .038.052v5.5826a4.504 4.504 0 0 1-4.4945 4.4944zm-9.6607-4.1254a4.4708 4.4708 0 0 1-.5346-3.0137l.142.0852 4.783 2.7582a.7712.7712 0 0 0 .7806 0l5.8428-3.3685v2.3324a.0804.0804 0 0 1-.0332.0615L9.74 19.9502a4.4992 4.4992 0 0 1-6.1408-1.6464zM2.3408 7.8956a4.485 4.485 0 0 1 2.3655-1.9728V11.6a.7664.7664 0 0 0 .3879.6765l5.8144 3.3543-2.0201 1.1685a.0757.0757 0 0 1-.071 0l-4.8303-2.7865A4.504 4.504 0 0 1 2.3408 7.872zm16.5963 3.8558L13.1038 8.364 15.1192 7.2a.0757.0757 0 0 1 .071 0l4.8303 2.7913a4.4944 4.4944 0 0 1-.6765 8.1042v-5.6772a.79.79 0 0 0-.407-.667zm2.0107-3.0231l-.142-.0852-4.7735-2.7818a.7759.7759 0 0 0-.7854 0L9.409 9.2297V6.8974a.0662.0662 0 0 1 .0284-.0615l4.8303-2.7866a4.4992 4.4992 0 0 1 6.6802 4.66zM8.3065 12.863l-2.02-1.1638a.0804.0804 0 0 1-.038-.0567V6.0742a4.4992 4.4992 0 0 1 7.3757-3.4537l-.142.0805L8.704 5.459a.7948.7948 0 0 0-.3927.6813zm1.0976-2.3654l2.602-1.4998 2.6069 1.4998v2.9994l-2.5974 1.4997-2.6067-1.4997Z\"/></svg>",
  "gemini-cli": "<svg viewBox=\"0 0 24 24\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M11.04 19.32Q12 21.51 12 24q0-2.49.93-4.68.96-2.19 2.58-3.81t3.81-2.55Q21.51 12 24 12q-2.49 0-4.68-.93a12.3 12.3 0 0 1-3.81-2.58 12.3 12.3 0 0 1-2.58-3.81Q12 2.49 12 0q0 2.49-.96 4.68-.93 2.19-2.55 3.81a12.3 12.3 0 0 1-3.81 2.58Q2.49 12 0 12q2.49 0 4.68.96 2.19.93 3.81 2.55t2.55 3.81\"/></svg>",
  "cursor": "<svg viewBox=\"0 0 466.73 532.09\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M457.43,125.94L244.42,2.96c-6.84-3.95-15.28-3.95-22.12,0L9.3,125.94c-5.75,3.32-9.3,9.46-9.3,16.11v247.99c0,6.65,3.55,12.79,9.3,16.11l213.01,122.98c6.84,3.95,15.28,3.95,22.12,0l213.01-122.98c5.75-3.32,9.3-9.46,9.3-16.11v-247.99c0-6.65-3.55-12.79-9.3-16.11h-.01ZM444.05,151.99l-205.63,356.16c-1.39,2.4-5.06,1.42-5.06-1.36v-233.21c0-4.66-2.49-8.97-6.53-11.31L24.87,145.67c-2.4-1.39-1.42-5.06,1.36-5.06h411.26c5.84,0,9.49,6.33,6.57,11.39h-.01Z\"/></svg>",
  "cline": "<svg viewBox=\"0 0 92 96\" fill=\"currentColor\" aria-hidden=\"true\"><g id=\"icon-copy\" transform=\"translate(-34, -40)\" fill=\"currentColor\"> <g id=\"Group-Copy-2\" transform=\"translate(34, 40.5)\"> <g id=\"Group-3-Copy-4\" transform=\"translate(0, 0)\"> <path d=\"M65.4492701,16.3 C76.3374701,16.3 85.1635558,25.16479 85.1635558,36.1 L85.1635558,42.7 L90.9027661,54.1647464 C91.4694141,55.2966923 91.4668177,56.6300535 90.8957658,57.7597839 L85.1635558,69.1 L85.1635558,75.7 C85.1635558,86.63554 76.3374701,95.5 65.4492701,95.5 L26.0206986,95.5 C15.1328272,95.5 6.30641291,86.63554 6.30641291,75.7 L6.30641291,69.1 L0.448507752,57.7954874 C-0.14693501,56.6464093 -0.149634367,55.2802504 0.441262896,54.1288283 L6.30641291,42.7 L6.30641291,36.1 C6.30641291,25.16479 15.1328272,16.3 26.0206986,16.3 L65.4492701,16.3 Z M62.9301895,22 L29.189529,22 C19.8723267,22 12.3191987,29.5552188 12.3191987,38.875 L12.3191987,44.5 L7.44288578,53.9634655 C6.84794449,55.1180686 6.85066096,56.4896598 7.45017099,57.6418974 L12.3191987,67 L12.3191987,72.625 C12.3191987,81.9450625 19.8723267,89.5 29.189529,89.5 L62.9301895,89.5 C72.2476729,89.5 79.8005198,81.9450625 79.8005198,72.625 L79.8005198,67 L84.5682187,57.6061395 C85.1432011,56.473244 85.1458141,55.1345713 84.5752587,53.9994398 L79.8005198,44.5 L79.8005198,38.875 C79.8005198,29.5552188 72.2476729,22 62.9301895,22 Z\" id=\"Combined-Shape\" fill-rule=\"nonzero\"></path> <circle id=\"Oval\" cx=\"45.7349843\" cy=\"11\" r=\"11\"></circle> </g> <rect id=\"Rectangle-Copy\" stroke=\"currentColor\" stroke-width=\"8\" x=\"31\" y=\"44.5\" width=\"5\" height=\"22\" rx=\"2.5\"></rect> <rect id=\"Rectangle-Copy-2\" stroke=\"currentColor\" stroke-width=\"8\" x=\"55\" y=\"44.5\" width=\"5\" height=\"22\" rx=\"2.5\"></rect> </g> </g></svg>",
  "aider": "<svg viewBox=\"0 0 13 17\" fill=\"currentColor\" aria-hidden=\"true\"><rect x=\"2\" y=\"0\" width=\"7\" height=\"1\"/><rect x=\"2\" y=\"1\" width=\"7\" height=\"1\"/><rect x=\"2\" y=\"2\" width=\"7\" height=\"1\"/><rect x=\"8\" y=\"3\" width=\"3\" height=\"1\"/><rect x=\"9\" y=\"4\" width=\"2\" height=\"1\"/><rect x=\"9\" y=\"5\" width=\"2\" height=\"1\"/><rect x=\"9\" y=\"6\" width=\"2\" height=\"1\"/><rect x=\"2\" y=\"7\" width=\"9\" height=\"1\"/><rect x=\"2\" y=\"8\" width=\"9\" height=\"1\"/><rect x=\"2\" y=\"9\" width=\"9\" height=\"1\"/><rect x=\"0\" y=\"10\" width=\"3\" height=\"1\"/><rect x=\"8\" y=\"10\" width=\"3\" height=\"1\"/><rect x=\"0\" y=\"11\" width=\"2\" height=\"1\"/><rect x=\"9\" y=\"11\" width=\"2\" height=\"1\"/><rect x=\"0\" y=\"12\" width=\"2\" height=\"1\"/><rect x=\"9\" y=\"12\" width=\"2\" height=\"1\"/><rect x=\"0\" y=\"13\" width=\"3\" height=\"1\"/><rect x=\"8\" y=\"13\" width=\"3\" height=\"1\"/><rect x=\"2\" y=\"14\" width=\"7\" height=\"1\"/><rect x=\"11\" y=\"14\" width=\"2\" height=\"1\"/><rect x=\"2\" y=\"15\" width=\"7\" height=\"1\"/><rect x=\"11\" y=\"15\" width=\"2\" height=\"1\"/><rect x=\"2\" y=\"16\" width=\"7\" height=\"1\"/><rect x=\"11\" y=\"16\" width=\"2\" height=\"1\"/></svg>",
  "opencode": "<svg viewBox=\"0 0 512 512\" fill=\"currentColor\" aria-hidden=\"true\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M384 416H128V96H384V416ZM320 160H192V352H320V160Z\"/></svg>",
  "pi": "<svg viewBox=\"0 0 800 800\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M165.29 165.29 H517.36 V400 H400 V517.36 H282.65 V634.72 H165.29 Z M282.65 282.65 V400 H400 V282.65 Z\"/><path d=\"M517.36 400 H634.72 V634.72 H517.36 Z\"/></svg>"
};

export const BRANDS: Record<string, Brand> = {
  "claude-code": {
    "bg": "#D97757",
    "fg": "#ffffff"
  },
  "codex": {
    "bg": "#0D0D0D",
    "fg": "#ffffff",
    "mono": true
  },
  "pi": {
    "bg": "#6B6864",
    "fg": "#ffffff"
  },
  "opencode": {
    "bg": "#121212",
    "fg": "#ffffff",
    "mono": true
  },
  "cursor": {
    "bg": "#0A0A0A",
    "fg": "#ffffff",
    "mono": true
  },
  "aider": {
    "bg": "#3FA45B",
    "fg": "#ffffff"
  },
  "cline": {
    "bg": "#2B2F36",
    "fg": "#ffffff",
    "mono": true
  },
  "gemini-cli": {
    "bg": "#1B72E8",
    "fg": "#ffffff"
  }
};

export const UI: Record<string, Bilingual> = {
  "title": {
    "zh": "Agent Harness 图鉴",
    "en": "Agent Harness Atlas"
  },
  "subtitle": {
    "zh": "主流 AI 编码 Agent 的 harness 能力对比",
    "en": "Harness capability comparison of mainstream AI coding agents"
  },
  "kicker": {
    "zh": "5 维 Harness 评测",
    "en": "5-Dim Harness Review"
  },
  "source": {
    "zh": "源码 + 官方文档分析",
    "en": "Source-code + official-docs analysis"
  },
  "matrix": {
    "zh": "能力矩阵",
    "en": "Capability Matrix"
  },
  "matrixSub": {
    "zh": "8 个 agent × 5 个维度",
    "en": "8 agents × 5 dimensions"
  },
  "legend": {
    "zh": "分数 0–100",
    "en": "Score 0–100"
  },
  "agentCol": {
    "zh": "Agent",
    "en": "Agent"
  },
  "scoreCol": {
    "zh": "综合",
    "en": "Overall"
  },
  "viewDetail": {
    "zh": "详情",
    "en": "Detail"
  },
  "backHome": {
    "zh": "返回矩阵",
    "en": "Back to matrix"
  },
  "updatedLabel": {
    "zh": "更新",
    "en": "Updated"
  },
  "evidence": {
    "zh": "证据指向",
    "en": "Evidence"
  },
  "conclusion": {
    "zh": "结论",
    "en": "Conclusion"
  },
  "vendor": {
    "zh": "厂商",
    "en": "Vendor"
  },
  "impl": {
    "zh": "实现",
    "en": "Built in"
  },
  "pending": {
    "zh": "待填",
    "en": "Pending"
  },
  "verdict": {
    "zh": "总评",
    "en": "Verdict"
  },
  "keep": {
    "zh": "亮点",
    "en": "strength"
  },
  "fix": {
    "zh": "不足",
    "en": "gap"
  },
  "testedVer": {
    "zh": "评测版本",
    "en": "Tested version"
  },
  "dimReports": {
    "zh": "逐维度报告",
    "en": "Dimension reports"
  },
  "dimReportsEn": {
    "zh": "每个维度的证据",
    "en": "Evidence per axis"
  },
  "radarLabel": {
    "zh": "评分雷达",
    "en": "Score Radar"
  },
  "overallLabel": {
    "zh": "综合",
    "en": "Overall"
  },
  "band": {
    "zh": "分段",
    "en": "band"
  },
  "disclaimer": {
    "zh": "当前为框架样本，分数与结论为占位估值，证据指向待填真实源码 / 文档分析。",
    "en": "Framework sample — scores & conclusions are placeholder estimates pending real source / doc analysis."
  },
  "dimCompare": {
    "zh": "在矩阵中横向对比",
    "en": "Compare in the matrix"
  },
  "themeLight": {
    "zh": "浅色",
    "en": "Light"
  },
  "themeDark": {
    "zh": "深色",
    "en": "Dark"
  },
  "weekly": {
    "zh": "每周更新",
    "en": "Updated weekly"
  }
};
