#!/usr/bin/env node
// F01 single-source check: prove there is exactly ONE authoritative AGENTS data
// definition (the generated module composed from analysis/*.json), that both
// pages reference the shared module, and that the build output exists.
import { readFileSync, existsSync, readdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const fail = (m) => {
  console.error(`✗ single-source: ${m}`);
  process.exit(1);
};

// 1. build output exists for both pages
for (const f of ["dist/index.html", "dist/agent.html"]) {
  if (!existsSync(resolve(ROOT, f))) fail(`missing build output ${f}`);
}

// 2. exactly one authoritative AGENTS array definition in src (the generated module)
const srcFiles = [];
const walk = (d) => {
  for (const e of readdirSync(d, { withFileTypes: true })) {
    const p = resolve(d, e.name);
    if (e.isDirectory()) walk(p);
    else if (/\.(ts|mjs|js)$/.test(e.name)) srcFiles.push(p);
  }
};
walk(resolve(ROOT, "src"));
const defining = srcFiles.filter((p) => /export const AGENTS\b/.test(readFileSync(p, "utf8")));
if (defining.length !== 1) {
  fail(`expected exactly 1 file with \`export const AGENTS\`, found ${defining.length}: ${defining.map((p) => p.replace(ROOT + "/", "")).join(", ")}`);
}
const authoritative = defining[0].replace(ROOT + "/", "");
if (authoritative !== "src/generated/atlas-data.ts") {
  fail(`authoritative AGENTS should be the generated module, but it's ${authoritative}`);
}

// 3. the generated module must be AUTO-GENERATED (not hand-authored data)
const gen = readFileSync(resolve(ROOT, "src/generated/atlas-data.ts"), "utf8");
if (!/AUTO-GENERATED by scripts\/build-data\.mjs/.test(gen)) fail("generated module missing AUTO-GENERATED banner");

// 4. no inline per-agent data array in the HTML templates (must come from the module)
for (const f of ["index.html", "agent.html"]) {
  const html = readFileSync(resolve(ROOT, f), "utf8");
  if (/const AGENTS\s*=/.test(html)) fail(`${f} still inlines an AGENTS array — must import the single source`);
  if (!/<script type="module"/.test(html)) fail(`${f} must load its page module via <script type="module">`);
}

// 5. both page entries import from the shared atlas module (which re-exports the single source)
for (const f of ["src/index.ts", "src/agent.ts"]) {
  const s = readFileSync(resolve(ROOT, f), "utf8");
  if (!/from "\.\/atlas"/.test(s)) fail(`${f} must import from the shared ./atlas module`);
}

// 6. agent count sanity: generated module agent count == analysis file count
const analysisCount = readdirSync(resolve(ROOT, "analysis")).filter((f) => f.endsWith(".json")).length;
const genCount = (gen.match(/"id":/g) || []).length >= analysisCount;
if (!genCount) fail("generated module has fewer agents than analysis/*.json files");

console.log(`✓ single-source: 1 authoritative module (${authoritative}); both pages import it; ${analysisCount} agents; dist built`);
